volumes:
  postgresql-data:
  manager-data:

services:
  postgresql:
    restart: always
    image: openremote/postgresql:latest
    shm_size: 512mb
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - manager-data:/storage
  keycloak:
    restart: always
    image: openremote/keycloak:latest
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8081:8080"
    volumes:
      - ./deployment:/deployment
    environment:
      KC_HOSTNAME: HOSTNAME
      KC_HOSTNAME_PORT: SSL_PORT
      KEYCLOAK_ADMIN_PASSWORD: PASSWORD
  manager:
    restart: always
    image: openremote/manager:latest
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "127.0.0.1:8405:8405" # Localhost metrics access
    volumes:
      - manager-data:/storage
    environment:
      OR_HOSTNAME: HOSTNAME
      OR_SSL_PORT: SSL_PORT
      OR_ADMIN_PASSWORD: PASSWORD
